### ISSUE TITLE
doesn't seem to work for company gmail accounts

### ISSUE THREAD

**Issue by lambtron** [zehfernandes/gifline#2]
i type

```
::gif me party
```

and it doesn't show anything. Is this different because of the gmail API?

Thanks, this really cool!

**Comment by zehfernandes** [comment]
Hey lambton.
In the [manifest.json](https://github.com/zehfernandes/gifline/blob/master/manifest.json), I declare just gmail pattern in "matches URL"

What is the pattern of the URL in company gmail?
I will think in some solution.

**Comment by lambtron** [comment]
oh interesting, i see. the company is segment.com. the email is andy@segment.com.

this is the URL i use to access gmail:

https://mail.google.com/mail/u/0/#all

Let me know if you need any more info!

**Comment by randalmaia** [comment]
Hey @lambtron, 

I tested on my company gmail and this doesn't happens. All work fine.
You could give more infos like browser, URL, console log or something strange?

Regards!
