### ISSUE TITLE
Support search by specific giphy ID

### ISSUE THREAD

**Issue by kpurdon** [zehfernandes/gifline#5]
For example:

`::gif me 3oEduXxyrVM2Lp76ow` would pull in the GIF with that ID which is: http://giphy.com/gifs/darkigloo-cat-kitten-kitty-3oEduXxyrVM2Lp76ow

**Comment by zehfernandes** [comment]
That's a good idea.

I will try to implement.

**Comment by zehfernandes** [comment]
Hey @kpurdon 

Did you think this feature is not useful anymore?

**Comment by kpurdon** [comment]
I would like it but was cleaning out old issues that haven't seen any action in a while that I have no intent of actually doing myself.
